name=HardwareSerial_v00x
version=0.0.1
author=R.Seelig
maintainer=
sentence=This is a library for CH32V003, missing UART-function
paragraph=This is a library for CH32V003, missing UART-function
category=Other
url=
architectures=*
depends=R.Seelig Arduino library for missing UART-function in CH32V003-core
